import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Script from "next/script";
import "../globals.css";
import HydrationFix from "@/components/shared/HydrationFix";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang='en'>
        <head>
          <Script
            src="/theme-init.js"
            strategy="beforeInteractive"
          />
        </head>
        <body className={`${inter.className} bg-dark-1`} suppressHydrationWarning={true} style={{visibility: 'hidden'}}>
          <HydrationFix />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}