import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Add error boundary for debugging
  if (!process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY) {
    console.error("NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY is not set");
  }
  
  if (!process.env.CLERK_SECRET_KEY) {
    console.error("CLERK_SECRET_KEY is not set");
  }

  return (
    <ClerkProvider
      // Add Clerk configuration to reduce session refresh issues
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      afterSignOutUrl="/"
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
    >
      <html lang='en'>
        <body className={`${inter.className}`} style={{backgroundColor: '#000', color: '#fff'}}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}